### ISSUE TITLE
[BUG][CIES] Inconsistent date formatting across the application

### ISSUE THREAD

**Issue by K1NGFR4NSITO** [K1NGFR4NSITO/cies-front#9]
Description: Sale dates are displayed in different formats across various parts of the application, causing confusion.

Steps to reproduce:

Navigate to the sales module.
Observe the date format in the sales table.
Compare it to the date format in the sales edit form.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Update date formatting to consistently use YYYY/MM/DD format across the sales module.

You can review changes in this commit: https://github.com/jjyutm4532/K1NGFR4NSITO-cies-front-9/commit/0ab08e5168b8d29f20bdce3320c8552d1a292f44.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
